In [233]:
import pandas as pd
import numpy as np

In [323]:
with open("day3ex2.txt", 'r') as f:
    data = f.read().splitlines()

In [324]:
mydict = {}
for i in range(len(data)):
    mydict[i] = [int(char) for char in data[i]]
data = pd.DataFrame.from_dict(mydict)

In [325]:
data = pd.DataFrame.from_dict(mydict)
dataT = data.T

In [326]:
data

0    1    2    3    4    5    6    7    8    9    ...  990  991  992  993  \
0     1    0    1    0    1    0    0    1    1    0  ...    0    1    1    1   
1     1    1    0    0    1    0    1    1    0    1  ...    1    1    1    0   
2     1    1    0    0    0    1    1    0    1    0  ...    1    0    1    1   
3     0    0    0    1    0    1    0    0    0    0  ...    0    1    0    0   
4     1    0    0    1    1    0    0    1    1    0  ...    1    0    1    0   
5     1    0    0    1    1    0    0    1    1    1  ...    1    0    1    1   
6     1    1    0    1    1    0    1    1    0    0  ...    1    1    0    1   
7     1    1    1    0    1    1    0    1    1    0  ...    1    0    0    0   
8     0    1    0    0    1    0    0    1    0    1  ...    0    0    1    0   
9     1    0    0    1    0    1    1    0    1    0  ...    0    0    0    1   
10    0    1    1    1    1    1    0    1    1    1  ...    0    0    0    1   
11    1    0    0    0    1    1    0    0    1    1  ...    1    0    1    0   

    994  995  996  997  998  999  
0     0    1    1    0    1    0  
1     1    1    0    0    0    0  
2     0    1    0    1    0    1  
3     0    1    0    1    1    1  
4     1    1    0    1    1    0  
5     0    1    1    0    1    1  
6     1    1    1    0    1    1  
7     1    1    0    0    0    0  
8     0    1    0    1    0    0  
9     1    1    1    1    1    0  
10    0    1    1    0    0    0  
11    1    0    0    1    1    1  

[12 rows x 1000 columns]

In [327]:
gamma_rate = dataT.mode().iloc[0].ravel()

In [328]:
gamma_rate

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1], dtype=int64)

In [329]:
epsilon_rate = np.where(gamma_rate==1, -1, gamma_rate)
epsilon_rate = np.where(epsilon_rate==0, 1, epsilon_rate)
epsilon_rate = np.where(epsilon_rate==-1, 0, epsilon_rate)
epsilon_rate, gamma_rate

(array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1], dtype=int64))

In [330]:
gamma, epsilon = 0, 0
def convert(mylist):
    result = 0
    for digit in mylist:
        result = (result << 1) | digit
    return result
gamma = convert(gamma_rate)
epsilon = convert(epsilon_rate)
gamma*epsilon

693486

In [331]:
# part2
dataT2 = dataT.copy()
for i in range(dataT2.shape[1]):
    mode=dataT2.mode()[i].ravel()
    if len(mode)==2:
        mode = 1
    else:
        mode = mode[0]
    dataT2 = dataT2[dataT2[i]==mode]
    if dataT2.shape[0] == 1:
        break
oxygen_gen = dataT2.values[0]
oxygen = convert(oxygen_gen)
oxygen

933

In [332]:
# part2
dataT2 = dataT.copy()
for i in range(dataT2.shape[1]):
    mode=dataT2.mode()[i].ravel()
    if len(mode)==1:
        mode = 0 if mode==1 else 1
    else:
        mode = 0
    dataT2 = dataT2[dataT2[i]==mode]
    if dataT2.shape[0] == 1:
        break
co2_gen = dataT2.values[0]
co2 = convert(co2_gen)
co2

3622

In [333]:
co2*oxygen

3379326